### ISSUE TITLE
App startup 2 minutes then crash

### ISSUE THREAD

**Issue by JordanPlayz158** [ComputerElite/QuestAppVersionSwitcher#17]
I recently updated to latest QuestAppVersionSwitcher from SideQuest as there seems to be some issues on the version I was running and now when I start up the app, it is black for 2 minutes and then crashes, here is the `adb logcat` output for your app: 
```
02-25 15:50:14.245  3355  3355 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:50:14.393  3355  3355 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:50:25.787  3355  3355 I [SUI] PanelAppBase: actionNavigate - App:  com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity, Uri:  
02-25 15:50:25.806  2719  2877 I [SEO] LaunchCommandHandler: Processing launch request as JSON.  Request args: {"componentName":"com.ComputerElite.questappversionswitcher\/crc64c3a6f1311d011724.MainActivity","timestamp":5277466,"skipDestinationUi":false}, sourcePanelId: 5
02-25 15:50:25.806  2719  2877 I [SEO] PanelAppLaunchInfo: PanelAppLaunchInfo componentString:com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity packageName:com.ComputerElite.questappversionswitcher serviceName:crc64c3a6f1311d011724.MainActivity componentName:com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity
02-25 15:50:25.806  2719  2877 I [SEO] HostPlatform: Retrieving component launch information for package (com.ComputerElite.questappversionswitcher) and service (crc64c3a6f1311d011724.MainActivity)
02-25 15:50:25.808  2719  2877 I [SEO] HostPlatform: Is valid panel service component for package (com.ComputerElite.questappversionswitcher) and service (crc64c3a6f1311d011724.MainActivity) - false
02-25 15:50:25.816  2719  2877 I [SEO] PanelAppLaunchInfo: PanelAppLaunchInfo componentString:com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity packageName:com.ComputerElite.questappversionswitcher serviceName:crc64c3a6f1311d011724.MainActivity componentName:com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity
02-25 15:50:25.816  2719  2877 I [SEO] HostPlatform: Retrieving component launch information for package (com.ComputerElite.questappversionswitcher) and service (crc64c3a6f1311d011724.MainActivity)
02-25 15:50:25.820  2719  2877 I [SEO] HostPlatform: Is valid panel service component for package (com.ComputerElite.questappversionswitcher) and service (crc64c3a6f1311d011724.MainActivity) - false
02-25 15:50:25.832  2719  2877 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:50:25.832  2719  2877 W [SEO] LibraryApiUtil: Unable to check whether package:com.ComputerElite.questappversionswitcher is an OCTV app.
02-25 15:50:25.833  2719  2877 I [SEO] LaunchController: VrDesktop launch for com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity.
02-25 15:50:25.834  2719  2877 I [SEO] LaunchController: Registering Pending Launch of type ShellApplication with com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity, overwriting existing launch false, of type None.
02-25 15:50:25.839  2719  2877 I [SEO] LaunchController: Building launch checks for com.ComputerElite.questappversionswitcher, activity or service: crc64c3a6f1311d011724.MainActivity, primary active package: com.oculus.shellenv
02-25 15:50:25.857  2719  2877 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:50:25.882  2719  2877 I [SEO] DesktopPanelController: LaunchOrRestore( com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity ) with launchAsNew=0, sourcePanelId=5, launchTarget=Default, targetMonitor=-1, launchingComponent=com.oculus.systemux/com.oculus.panelapp.library.LibraryPanelService
02-25 15:50:25.882  2719  2877 I [SEO] PanelAppsManager: ActivatePanelApp for component com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity. New instance requested: 0
02-25 15:50:25.882  2719  2877 I [SEO] PanelAppsManager: launching new instance of com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity
02-25 15:50:25.882  2719  2877 I [SEO] ShellApp: CreatePanelApp( com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity )
02-25 15:50:25.882  2719  2877 I [SEO] ShellApp: Environment:
02-25 15:50:25.882  2719  2877 I [SEO] ShellApp: uri = com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity
02-25 15:50:25.882  2719  2877 I [SEO] ShellApp: _oc_launch_timestamp = 5277485
02-25 15:50:25.882  2719  2877 I [SEO] ShellApp: intent_data = com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity
02-25 15:50:25.883  2719  2877 I [SEO] PanelAppHost: PanelAppHost constructor, panel 85 (com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity)
02-25 15:50:25.883  2719  2877 I [SEO] PanelAppHost: Panel app 85 (com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity) changing state from startup to foreground
02-25 15:50:25.886  2719  2877 I [SEO] PanelAppHost: Passing env var uri = com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity
02-25 15:50:25.886  2719  2877 I [SEO] PanelAppHost: Passing env var intent_data = com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity
02-25 15:50:25.886  2719  2877 I [SEO] PanelAppHost: Calling sendPanelLaunchIntent for panel app 85 (com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity)
02-25 15:50:25.893  2719  2877 I [SEO] DesktopPanelController: Checking whether desktop switch is necessary with current desktop Multi-app for activation of app com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity
02-25 15:50:25.893  2719  2877 I [SEO] DesktopPanelController: Initial cooperative state for app com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity with uri com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity is cooperative
02-25 15:50:25.893  2719  2877 I [SEO] AppActivationRecord: AppActivation result is Success with reason  and type:Launch, launchTarget:Default, activationSourceId:5, activationTargetId:2, launchAsNew:0, uri:com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity, launchingComponent:com.oculus.systemux/com.oculus.panelapp.library.LibraryPanelService
02-25 15:50:25.894  2719  2877 I [SEO] DesktopFocusManager: Notifying panel with id:85, component:com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity of isFocused:1
02-25 15:50:25.895  2719  2877 I [SEO] PanelAppAnalytics: First frame latency: 0.012 for id 85 com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity
02-25 15:50:25.902  2719  2877 I [SEO] DesktopAnimationController: Playing launch animation with delay=1 for panel with id 85 and name com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity
02-25 15:50:25.904  3355  3355 D [SUI] AnytimeUIAndroidPanelApp: Received appStatus from VrShell: [{"name":"com.oculus.explore\/com.oculus.explore.PanelService","panels":[{"panelId":3,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.quicksettings.QuickSettingsPanelService","panels":[{"panelId":9,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.library.LibraryPanelService","panels":[{"panelId":5,"state":"Foreground"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.settings.SettingsPanelService","panels":[{"panelId":53,"state":"Background"}]},{"name":"com.weloveoculus.BMBF\/com.weloveoculus.BMBF.MainActivity","panels":[{"panelId":36,"state":"Background"}]},{"name":"com.android.settings\/com.oculus.vrshell.desktop.PanelService","panels":[{"panelId":46,"state":"Background"}]},{"name":"com.oculus.browser\/com.oculus.browser.PanelService","panels":[{"panelId":49,"state":"Background"}]},{"name":"com.ComputerElite.questappversionswitcher\/crc64c3a6f1311d011724.MainActivity","panels":[{"panelId":85,"state":"Focused"}]}]
02-25 15:50:25.927  4153  4153 I VrDesktopPanelApp-ShellEnvironment: ShellEnvironment{width=-1 height=-1 shape=-1 density=-1 screenScale=1.000000 renderScale=1.250000 isInOverlay=false isSuperSamplingEnabled=false isBackNavigationEnabled=false targetUri=com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity analyticsSessionId=84694438-1fe7-4b4b-b2e9-89b15e1e750d}
02-25 15:50:25.937  4153  4153 D VrDesktopPanelApp-AppProperties: Finding app properties for package:com.ComputerElite.questappversionswitcher.
02-25 15:50:25.977  3355  3355 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:50:26.006  4153  4153 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:50:26.006  4153  4153 D VrDesktopPanelApp-AppProperties: Oculus library app not found for package:com.ComputerElite.questappversionswitcher.
02-25 15:50:26.012  4153  4153 I VrDesktopPanelApp-Java: Target: LaunchConfiguration{w=800 h=500 shape=2 dpi=160 scale=1.250000 intent=Intent { flg=0x14000000 cmp=com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity (has extras) }}
02-25 15:50:26.029  2719  2877 I [SEO] PanelAppHost: Setting panel layer visibility of layer "#main" to invisible, panel 85 (com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity)
02-25 15:50:26.029  2719  2877 I [SEO] PanelAppHost: Resize layer #main to size 1000 x 625 shape: 2 stereo: 0, panel 85 (com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity)
02-25 15:50:26.030  2719  2877 I [SEO] PanelAppHost: Setting panel layer visibility of layer "#main" to visible, panel 85 (com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity)
02-25 15:50:26.240  3355 18063 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:50:26.261  1050  1337 D VrDesktopService: startActivity(): Intent { flg=0x14000000 cmp=com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity (has extras) }
02-25 15:50:26.362  1050  1337 I ActivityTaskManager: START u0 {flg=0x14000000 cmp=com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity (has extras)} from uid 1000
02-25 15:50:26.596  3355  3355 D [SUI] AnytimeUIAndroidPanelApp: Received appStatus from VrShell: [{"name":"com.oculus.explore\/com.oculus.explore.PanelService","panels":[{"panelId":3,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.quicksettings.QuickSettingsPanelService","panels":[{"panelId":9,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.library.LibraryPanelService","panels":[{"panelId":5,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.settings.SettingsPanelService","panels":[{"panelId":53,"state":"Background"}]},{"name":"com.weloveoculus.BMBF\/com.weloveoculus.BMBF.MainActivity","panels":[{"panelId":36,"state":"Background"}]},{"name":"com.android.settings\/com.oculus.vrshell.desktop.PanelService","panels":[{"panelId":46,"state":"Background"}]},{"name":"com.oculus.browser\/com.oculus.browser.PanelService","panels":[{"panelId":49,"state":"Background"}]},{"name":"com.ComputerElite.questappversionswitcher\/crc64c3a6f1311d011724.MainActivity","panels":[{"panelId":85,"state":"Focused"}]}]
02-25 15:50:26.654  1050  1083 I ActivityManager: Start proc 18077:com.ComputerElite.questappversionswitcher/u0a117 for activity {com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity}
02-25 15:50:26.691  3355  3355 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:50:26.967  3355 18063 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:51:14.268  3355  3355 D [SUI] AnytimeUIAndroidPanelApp: Received appStatus from VrShell: [{"name":"com.oculus.explore\/com.oculus.explore.PanelService","panels":[{"panelId":3,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.quicksettings.QuickSettingsPanelService","panels":[{"panelId":9,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.library.LibraryPanelService","panels":[{"panelId":5,"state":"Background"}]},{"name":"com.weloveoculus.BMBF\/com.weloveoculus.BMBF.MainActivity","panels":[{"panelId":36,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.settings.SettingsPanelService","panels":[{"panelId":53,"state":"Background"}]},{"name":"com.oculus.vrshell\/com.oculus.panelapp.shellhomeux.ShellHomeUXPanelService","panels":[{"panelId":86,"state":"Foreground"}]},{"name":"com.android.settings\/com.oculus.vrshell.desktop.PanelService","panels":[{"panelId":46,"state":"Background"}]},{"name":"com.oculus.browser\/com.oculus.browser.PanelService","panels":[{"panelId":49,"state":"Background"}]},{"name":"com.ComputerElite.questappversionswitcher\/crc64c3a6f1311d011724.MainActivity","panels":[{"panelId":85,"state":"Focused"}]}]
02-25 15:51:14.356  3355  3355 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:51:14.893  3355 18063 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:52:07.653 18077 18077 E AndroidRuntime: FATAL EXCEPTION: main
02-25 15:52:07.653 18077 18077 E AndroidRuntime: Process: com.ComputerElite.questappversionswitcher, PID: 18077
02-25 15:52:07.653 18077 18077 E AndroidRuntime: android.runtime.JavaProxyThrowable: System.Net.WebException: The operation has timed out.
02-25 15:52:07.653 18077 18077 E AndroidRuntime:   at System.Net.HttpWebRequest.RunWithTimeoutWorker[T] (System.Threading.Tasks.Task`1[TResult] workerTask, System.Int32 timeout, System.Action abort, System.Func`1[TResult] aborted, System.Threading.CancellationTokenSource cts) [0x000f8] in <fd5c6c3fb3f749639789243858b772b4>:0 
02-25 15:52:07.653 18077 18077 E AndroidRuntime:   at System.Net.HttpWebRequest.GetResponse () [0x00016] in <fd5c6c3fb3f749639789243858b772b4>:0 
02-25 15:52:07.653 18077 18077 E AndroidRuntime:   at System.Net.WebClient.GetWebResponse (System.Net.WebRequest request) [0x00000] in <fd5c6c3fb3f749639789243858b772b4>:0 
02-25 15:52:07.653 18077 18077 E AndroidRuntime:   at System.Net.WebClient.DownloadBits (System.Net.WebRequest request, System.IO.Stream writeStream) [0x000e6] in <fd5c6c3fb3f749639789243858b772b4>:0 
02-25 15:52:07.653 18077 18077 E AndroidRuntime:   at System.Net.WebClient.DownloadFile (System.Uri address, System.String fileName) [0x00088] in <fd5c6c3fb3f749639789243858b772b4>:0 
02-25 15:52:07.653 18077 18077 E AndroidRuntime:   at (wrapper remoting-invoke-with-check) System.Net.WebClient.DownloadFile(System.Uri,string)
02-25 15:52:07.653 18077 18077 E AndroidRuntime:   at QuestAppVersionSwitcher.Mods.ExternalFilesDownloader.DownloadUrl (System.String downloadUrlString, System.String path) [0x0000d] in <2fbd680fb1c0485f9a2c528e739ddeac>:0 
02-25 15:52:07.653 18077 18077 E AndroidRuntime:   at QuestAppVersionSwitcher.Core.CoreService.Start () [0x0034e] in <2fbd680fb1c0485f9a2c528e739ddeac>:0 
02-25 15:52:07.653 18077 18077 E AndroidRuntime:   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) [0x00000] in <2c2265bcf0434520b942c9dd009b09ae>:0 
02-25 15:52:07.653 18077 18077 E AndroidRuntime:   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <a1626aa055c04b568e547175a4e3713a>:0 
02-25 15:52:07.653 18077 18077 E AndroidRuntime:   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <a1626aa055c04b568e547175a4e3713a>:0 
02-25 15:52:07.653 18077 18077 E AndroidRuntime:   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <a1626aa055c04b568e547175a4e3713a>:0 
02-25 15:52:07.653 18077 18077 E AndroidRuntime:   at Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PP_V (_JniMarshal_PP_V callback, System.IntPtr jnienv, System.IntPtr klazz) [0x00005] in <a1626aa055c04b568e547175a4e3713a>:0 
02-25 15:52:07.653 18077 18077 E AndroidRuntime: 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
02-25 15:52:07.653 18077 18077 E AndroidRuntime: 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:31)
02-25 15:52:07.653 18077 18077 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:886)
02-25 15:52:07.653 18077 18077 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-25 15:52:07.653 18077 18077 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:227)
02-25 15:52:07.653 18077 18077 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7436)
02-25 15:52:07.653 18077 18077 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-25 15:52:07.653 18077 18077 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-25 15:52:07.653 18077 18077 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
02-25 15:52:07.670  1050  4987 W ActivityTaskManager:   Force finishing activity com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity
02-25 15:52:07.694  1050  1162 W InputDispatcher: channel 'aef27f9 com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-25 15:52:07.694  1050  1162 E InputDispatcher: channel 'aef27f9 com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-25 15:52:07.695  1050  4322 I WindowManager: WIN DEATH: Window{aef27f9 u0 com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity}
02-25 15:52:07.695  1050  4322 W InputDispatcher: Attempted to unregister already unregistered input channel 'aef27f9 com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity (server)'
02-25 15:52:07.697  1050 21951 I ActivityManager: Process com.ComputerElite.questappversionswitcher (pid 18077) has died: fore  +1 TOP 
02-25 15:52:07.738  2719  2877 I [SEO] PanelAppHost: Exiting panel application 85 (com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity) on next frame with reason App Closed.
02-25 15:52:07.739  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.749  2719  2877 I [SEO] VrShellDesktopBase: Remove panelApp: com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity from monitor 2
02-25 15:52:07.749  2719  2877 I [SEO] DesktopAnimationController: Playing close animation for exiting panel with id 85 and name com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity
02-25 15:52:07.749  2719  2877 I [SEO] DesktopFocusManager: Notifying panel with id:85, component:com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity of isFocused:0
02-25 15:52:07.749  2719  2877 W [SEO] PanelAppHost: We are losing an exit reason (App Closed) because we are already exiting (App Closed). Panel 85 (com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity)
02-25 15:52:07.750  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.751  3355  3355 D [SUI] AnytimeUIAndroidPanelApp: Received appStatus from VrShell: [{"name":"com.oculus.explore\/com.oculus.explore.PanelService","panels":[{"panelId":3,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.quicksettings.QuickSettingsPanelService","panels":[{"panelId":9,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.library.LibraryPanelService","panels":[{"panelId":5,"state":"Background"}]},{"name":"com.weloveoculus.BMBF\/com.weloveoculus.BMBF.MainActivity","panels":[{"panelId":36,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.settings.SettingsPanelService","panels":[{"panelId":53,"state":"Background"}]},{"name":"com.oculus.vrshell\/com.oculus.panelapp.shellhomeux.ShellHomeUXPanelService","panels":[{"panelId":86,"state":"Foreground"}]},{"name":"com.android.settings\/com.oculus.vrshell.desktop.PanelService","panels":[{"panelId":46,"state":"Background"}]},{"name":"com.oculus.browser\/com.oculus.browser.PanelService","panels":[{"panelId":49,"state":"Background"}]},{"name":"com.ComputerElite.questappversionswitcher\/crc64c3a6f1311d011724.MainActivity","panels":[{"panelId":85,"state":"Focused"}]}]
02-25 15:52:07.762  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.784  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.794  1769  1910 I crash-reporter: uncaught drop box entry crash report written at /data/misc/crashes/7264dae6-d5a9-4507-86f1-55a8280a9322_com.ComputerElite.questappversionswitcher_2023-02-25_15-52-07-735726.exception.meta
02-25 15:52:07.795  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.840  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.851  3355  3355 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:52:07.851  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.873  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.884  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.896  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.929  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.940  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.951  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.952  3355  3355 D [SUI] AnytimeUIAndroidPanelApp: Received appStatus from VrShell: [{"name":"com.oculus.explore\/com.oculus.explore.PanelService","panels":[{"panelId":3,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.quicksettings.QuickSettingsPanelService","panels":[{"panelId":9,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.library.LibraryPanelService","panels":[{"panelId":5,"state":"Background"}]},{"name":"com.weloveoculus.BMBF\/com.weloveoculus.BMBF.MainActivity","panels":[{"panelId":36,"state":"Background"}]},{"name":"com.oculus.systemux\/com.oculus.panelapp.settings.SettingsPanelService","panels":[{"panelId":53,"state":"Background"}]},{"name":"com.oculus.vrshell\/com.oculus.panelapp.shellhomeux.ShellHomeUXPanelService","panels":[{"panelId":86,"state":"Foreground"}]},{"name":"com.android.settings\/com.oculus.vrshell.desktop.PanelService","panels":[{"panelId":46,"state":"Background"}]},{"name":"com.oculus.browser\/com.oculus.browser.PanelService","panels":[{"panelId":49,"state":"Background"}]},{"name":"com.ComputerElite.questappversionswitcher\/crc64c3a6f1311d011724.MainActivity","panels":[{"panelId":85,"state":"Foreground"}]}]
02-25 15:52:07.962  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.996  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:07.999  3355 18063 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:52:07.999  3355  3355 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:52:08.007  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:08.041  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:08.052  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:08.063  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:08.096  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:08.109  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:08.140  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:08.152  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:08.163  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:08.253  2719  2877 I [SEO] PanelAppHost: ExitNextFrame triggered on panel com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 for reason App Closed
02-25 15:52:08.262  2719  2877 I [SEO] PanelAppsManager: com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity:85 will be destroyed
02-25 15:52:08.262  2719  2877 I [SEO] PanelAppHost: PanelAppHost destructor, panel 85 (com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity)
02-25 15:52:08.262  2719  2877 I [SEO] PanelAppHost: Panel app 85 (com.ComputerElite.questappversionswitcher/crc64c3a6f1311d011724.MainActivity) changing state from foreground to shutdown
02-25 15:52:08.390  3355  3355 W OVRLibrary: null cursor received for query content://com.oculus.ocms.library/apps/com.ComputerElite.questappversionswitcher
02-25 15:52:08.707   817   990 I crash-uploader: Crash uploaded from /data/misc/crashes//7264dae6-d5a9-4507-86f1-55a8280a9322_com.ComputerElite.questappversionswitcher_2023-02-25_15-52-07-735726.exception.meta to https://b-www.facebook.com/mobile/reliability_event_log_upload/
```

**Comment by ComputerElite** [comment]
Could you try restarting your quest?

**Comment by ComputerElite** [comment]
Or if it's an issue with an app installed by QuestAppVersionSwitcher there's nothing I can do

**Comment by JordanPlayz158** [comment]
It was an internet issue, devices on my LAN had IPv6 addresses but were unable to access IPv6 sites (which I assume android and/or quest prefers IPv6 over IPv4) and it caused the issue.

This article helped me fix my issue (relevant for pfSense or OPNSense users (not sure about people who use standard routers)):
https://homenetworkguy.com/how-to/configure-ipv6-opnsense-with-isp-such-as-comcast-xfinity/

The easy way to test if you have IPv6 working is by going to https://ip6.me and clicking on IPv6 only test hyperlink.
